apiVersion: v1
kind: Service
metadata:
  name: hello-uname
  labels:
    app: hello-uname
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: external
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    service.beta.kubernetes.io/aws-load-balancer-ip-address-type: dualstack
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: {{ .Values.helloUname.certARN }}
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: https
    service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags: Name=hello-uname,Owner=makotom
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.helloUname.hostname }}
spec:
  type: LoadBalancer
  ports:
    - port: 443
      targetPort: 8080
      protocol: TCP
      name: https
  selector:
    app: hello-uname
